[Icon Theme]
Name=OriginUi Radiance
Comment=Radiance for OriginUi
Inherits=Adwaita
Example=folder

# KDE/Plasma Stuff
DisplayDepth=32
LinkOverlay=link_overlay
LockOverlay=lock_overlay
ZipOverlay=zip_overlay
DesktopDefault=48
DesktopSizes=16,22,32,48,64,96,128,256
ToolbarDefault=22
ToolbarSizes=16,22,32,48
MainToolbarDefault=22
MainToolbarSizes=16,22,32,48
SmallDefault=16
SmallSizes=16,22,32,48
PanelDefault=48
PanelSizes=16,22,32,48,64,96,128,256
DialogDefault=32
DialogSizes=16,22,32,48,64,128,256
FollowsColorScheme=true

KDE-Extensions=.svg

# Directory list
Directories=apps,actions/symbolic/scalable,status/symbolic/scalable,devices,scalable/places,scalable/mimetypes

[apps]
Size=64
Context=Applications
MinSize=16
MaxSize=256
Type=Scalable

[actions/symbolic/scalable]
Size=32
Context=Actions
MinSize=16
MaxSize=256
Type=Scalable

[status/symbolic/scalable]
Size=64
Context=Status
MinSize=16
MaxSize=256
Type=Scalable

[devices]
Size=64
Context=Devices
MinSize=16
MaxSize=256
Type=Scalable

[scalable/places]
Size=64
Context=Places
MinSize=16
MaxSize=256
Type=Scalable

[scalable/mimetypes]
Size=64
Context=MimeTypes
MinSize=16
MaxSize=256
Type=Scalable
